### ISSUE TITLE
Problems with Qsci

### ISSUE THREAD

**Issue by alexandreborges** [techbliss/Python_editor#1]
Dear developer, 

Good morning. How are you? 

Even after installing from https://mega.nz/#!Dt9xHD7D!bwZVrOd4H4EpsW9c3iz1rU9R_x_LogYQMto8wu6IF4c , I have faced the following message while trying to call the ALT+E shortcut:

cannot import name Qsci
Traceback (most recent call last):
  File "C:\Program Files (x86)\IDA 6.95\python\ida_idaapi.py", line 509, in IDAPython_ExecScript
    execfile(script, g)
  File "C:\Program Files (x86)\IDA 6.95\plugins\Code editor\pyeditor.py", line 44, in <module>
    from PyQt5 import QtCore, QtGui, Qsci, QtWidgets, Qt
**ImportError: cannot import name Qsci**

The environment is a Win7x64 SP1 with Python 2.7. Additionally, my IDA Pro is 6.95.

Thank you and have a nice day.

Alex.

**Comment by techbliss** [comment]
thank you i am fine.
Do you have added you /site-packages/PyQt5 folder to your system envvar path.
also to you have both Qsci.py and Qscintilla2.dll in the PyQt5 root folder /site-packages/PyQt5.

if it dont work after adding folder to envar try put these in that folder, however they should be exactly the same as the installer ones.

[qscintilla2.zip](https://github.com/techbliss/Python_editor/files/752242/qscintilla2.zip)

    >>> from PyQt5 import Qsci
    >>> help ('PyQt5.Qsci')
    Help on module PyQt5.Qsci in PyQt5:

    NAME
        PyQt5.Qsci

    FILE
        c:\python27\lib\site-packages\pyqt5\qsci.pyd

    CLASSES
        PyQt5.QtCore.QObject(sip.wrapper)
            QsciAbstractAPIs
             QsciAPIs
            QsciLexer
            QsciLexerAVS
            QsciLexerBash
            QsciLexerBatch
             QsciLexerCMake
                 QsciLexerCPP
               QsciLexerCSharp
              QsciLexerIDL
             QsciLexerJava
             QsciLexerJavaScript
            QsciLexerCSS
            QsciLexerCoffeeScript
            QsciLexerCustom
            QsciLexerD
            QsciLexerDiff
            QsciLexerFortran77
                QsciLexerFortran
    -- More  --

Also it could be a incident where it finds another qsci.pyd or Qscintilla2.dll in your system.before it loads the ones found in PyQt5 folder.

**Comment by techbliss** [comment]
after i could reproduce the same problem on a new laptop i made a new build for PyQt5.


it ain't as big as the previous build.
Can you test this build and see if it fixes your problems.It aint a installer just a zipped build of PyQt5 for ida
https://mega.nz/#!PsMUhLwB!hr2Nzuj-i7eEPIrdPv6hfchq3_OUDWcCTrr2D0_S2Ik


if you get the error Qt platform plugin "windows" not found
add to envar 
QT_QPA_PLATFORM_PLUGIN_PATH=C:\Python27\lib\site-packages\PyQt5\platforms
