### ISSUE TITLE
Please help me.

### ISSUE THREAD

**Issue by nihuai** [techbliss/Python_editor#2]
@techbliss 
My IDA version is 6.8，
My Python version is 2.7.13
Can you provide the latest idapython plugin? I can't compile!
The plugin author has not updated  for a long time 
Failed to install using the old plug-in，It could be the python version problem
Script editor rely on idapython  plugin？

**Comment by techbliss** [comment]
https://github.com/idapython/bin 1.7.2

**Comment by nihuai** [comment]
The bin directory has not been updated for a long time
After I downloaded the installation failed, that is, 1.7.2
Plugins do not support，python2.7.13？

**Comment by techbliss** [comment]
Script rely on PyQt and Qsci Pyqt module explained in readme.
