### ISSUE TITLE
Not work for Windows

### ISSUE THREAD

**Issue by Cxk4ng** [techbliss/Python_editor#5]
Unable to locate program entry point ?setSelectionMode@QAbstractItemView@QT@@QEAAXW4SelectionMode@12@@Z Dynamic link library D:\IDA 7.0\ida.exe。 
Unable to locate program entry point ?staticMetaObject@QLineEdit@QT@@2UQMetaObject@2@B Dynamic link library D:\IDA 7.0\Qt5PrintSupport.dll。 

It took two days , not solved
Use now pycharm edit 。。。。

**Comment by techbliss** [comment]
Its in the readme on first page

> IMPORTANT! you have to take Qt5Core.dll , Qt5Gui.dll, Qt5widgets.dll, Qt5PrintSupport.dll from PyQt5 package and overwrite the ones in ida pro 7.0 folder
