### ISSUE TITLE
  File "F:\BaiduNetdiskDownload\IDA 7.0\IDA_Pro_v7.0_Portable\plugins\Code editor\pyeditor.py", line 56, in <module>     from PyQt5.Qsci import QsciScintilla, QsciLexerPython ImportError: DLL load failed: �Ҳ���ָ���ĳ�����

### ISSUE THREAD

**Issue by kailicard** [techbliss/Python_editor#7]
File "F:\BaiduNetdiskDownload\IDA 7.0\IDA_Pro_v7.0_Portable\plugins\Code editor\pyeditor.py", line 56, in <module>
    from PyQt5.Qsci import QsciScintilla, QsciLexerPython
ImportError: DLL load failed: �Ҳ���ָ���ĳ�����

**Comment by techbliss** [comment]
Hello.
It says in the readme on front page 

**It needs Qscilla module(Qsci.pyd), not provided by hex-ray, but found in the links under.**

**Pyqt4 installer**

[Pyqt4](http://www.techbliss.org/threads/pyqt-win-gpl-4-11-qt-4-4-8-7-for-ida-pro-total-package-installer-by-storm-shadow.768/)

**Pyqt5 installer**

[Pyqt5](https://www.techbliss.org/threads/ida-pro-pyqt5-5-6-2-x32-complete-installer-package-by-storm-shadow.909/#post-3114)

[Pyqt5 ida pro 7.0](https://www.techbliss.org/threads/ida-pro-7-0-pyqt5-total-package-by-storm-shadow.950/)

**Comment by kailicard** [comment]
Thank you,I have done it after receved your email

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Storm Shadow <notifications@github.com>
发送时间: Monday, May 6, 2019 1:32:49 AM
收件人: techbliss/Python_editor
抄送: kailicard; Author
主题: Re: [techbliss/Python_editor] File "F:\BaiduNetdiskDownload\IDA 7.0\IDA_Pro_v7.0_Portable\plugins\Code editor\pyeditor.py", line 56, in <module> from PyQt5.Qsci import QsciScintilla, QsciLexerPython ImportError: DLL load failed: �Ҳ���ָ���ĳ����� (#7)


Hello.
It says in the readme on front page

It needs Qscilla module(Qsci.pyd), not provided by hex-ray, but found in the links under.

Pyqt4 installer

Pyqt4<http://www.techbliss.org/threads/pyqt-win-gpl-4-11-qt-4-4-8-7-for-ida-pro-total-package-installer-by-storm-shadow.768/>

Pyqt5 installer

Pyqt5<https://www.techbliss.org/threads/ida-pro-pyqt5-5-6-2-x32-complete-installer-package-by-storm-shadow.909/#post-3114>

Pyqt5 ida pro 7.0<https://www.techbliss.org/threads/ida-pro-7-0-pyqt5-total-package-by-storm-shadow.950/>
